# Generated by Django 5.2.9 on 2025-12-21 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField()),
                ('payout', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('SETTLED', 'SETTLED'), ('CANCELLED', 'CANCELLED')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.game')),
                ('pick_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='uniq_bet_per_user_per_game')],
            },
        ),
    ]
