# Generated by Django 5.2.9 on 2025-12-19 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='placed_at',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='points',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='status',
        ),
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bet',
            name='result',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('W', 'Win'), ('L', 'Lose')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bet',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.game'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='payout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='pick_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picked_bets', to='games.team'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['game', 'settled'], name='betting_bet_game_id_2d8e73_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'created_at'], name='betting_bet_user_id_728335_idx'),
        ),
        migrations.DeleteModel(
            name='MonthlyScore',
        ),
    ]
