# Generated by Django 5.2.9 on 2025-12-22 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bet',
            name='uniq_bet_per_user_per_game',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='pick_team',
        ),
        migrations.AddField(
            model_name='bet',
            name='odds_x100',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='bet',
            name='pick',
            field=models.CharField(choices=[('home', 'Home Win'), ('away', 'Away Win')], default='home', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bet',
            name='payout',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status'], name='betting_bet_status_69d9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'created_at'], name='betting_bet_user_id_728335_idx'),
        ),
    ]
