# Generated by Django 5.2.9 on 2025-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_alter_monthlyscore_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bet',
            name='betting_bet_game_id_2d8e73_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='betting_bet_user_id_728335_idx',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='result',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='settled',
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.PositiveIntegerField(),
        ),
    ]
