# Generated by Django 5.2.9 on 2025-12-22 11:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailycheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettx',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet_place', 'Bet Place'), ('bet_win', 'Bet Win'), ('bet_refund', 'Bet Refund'), ('daily_bonus', 'Daily Bonus'), ('adjust', 'Adjust')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('ref', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='accounts.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyCheckin',
        ),
        migrations.DeleteModel(
            name='WalletTx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='accounts_tr_wallet__6a4681_idx'),
        ),
    ]
