# Generated by Django 5.2.9 on 2025-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_wallettx_wallet_wallet_last_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet_place', 'Bet Place'), ('bet_win', 'Bet Win'), ('bet_refund', 'Bet Refund'), ('daily_bonus', 'Daily Bonus'), ('shop_buy', 'Shop Buy'), ('lootbox', 'Loot Box'), ('adjust', 'Adjust')], max_length=20),
        ),
    ]
