# Generated by Django 5.2.9 on 2025-12-22 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_tx_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=30)),
                ('amount', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_txs', to='accounts.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
