# Generated by Django 5.2.9 on 2025-12-22 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyscore',
            options={'ordering': ('-profit', '-wins', '-volume', 'user_id')},
        ),
        migrations.RemoveIndex(
            model_name='monthlyscore',
            name='leaderboard_month_130ed9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyscore',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='monthlyscore',
            index=models.Index(fields=['month'], name='leaderboard_month_403d15_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyscore',
            index=models.Index(fields=['user', 'month'], name='leaderboard_user_id_2520c5_idx'),
        ),
    ]
