# Generated by Django 5.2.9 on 2025-12-15 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysnapshotrow',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='monthlysnapshotrow',
            name='user',
        ),
        migrations.CreateModel(
            name='MonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySnapshot',
        ),
        migrations.DeleteModel(
            name='MonthlySnapshotRow',
        ),
        migrations.AddIndex(
            model_name='monthlyscore',
            index=models.Index(fields=['year', 'month', '-points'], name='leaderboard_year_54f9d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyscore',
            unique_together={('user', 'year', 'month')},
        ),
    ]
