# Generated by Django 5.2.9 on 2025-12-19 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_monthlysnapshotrow_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyscore',
            options={'ordering': ('-score', 'user_id')},
        ),
        migrations.RemoveIndex(
            model_name='monthlyscore',
            name='leaderboard_year_54f9d2_idx',
        ),
        migrations.RenameField(
            model_name='monthlyscore',
            old_name='points',
            new_name='score',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyscore',
            unique_together={('user', 'month')},
        ),
        migrations.AlterField(
            model_name='monthlyscore',
            name='month',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.RemoveField(
            model_name='monthlyscore',
            name='year',
        ),
    ]
