# Generated by Django 5.2.9 on 2025-12-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('espn', 'ESPN')], default='espn', max_length=20)),
                ('source_team_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('abbr', models.CharField(blank=True, default='', max_length=10)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_team_id'), name='uniq_team_source_id')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('espn', 'ESPN')], default='espn', max_length=20)),
                ('source_game_id', models.CharField(db_index=True, max_length=64)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('final', 'Final'), ('postponed', 'Postponed'), ('canceled', 'Canceled'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='games.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='games.team')),
            ],
            options={
                'ordering': ('-start_time', '-id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'source_game_id'), name='uniq_game_source_id')],
            },
        ),
    ]
